create table if not exists public.portal_execution_tasks (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.portal_customers(id) on delete cascade,
  task_code text not null,
  is_completed boolean not null default false,
  completed_at timestamptz,
  note text,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id),
  unique (customer_id, task_code)
);

create index if not exists idx_execution_tasks_customer
  on public.portal_execution_tasks (customer_id, updated_at desc);

alter table public.portal_execution_tasks enable row level security;

drop policy if exists "portal_execution_tasks_select" on public.portal_execution_tasks;
create policy "portal_execution_tasks_select"
on public.portal_execution_tasks
for select
using (
  public.portal_is_admin()
  or customer_id = public.portal_my_customer_id()
);

drop policy if exists "portal_execution_tasks_write" on public.portal_execution_tasks;
create policy "portal_execution_tasks_write"
on public.portal_execution_tasks
for all
using (
  public.portal_is_admin()
  or customer_id = public.portal_my_customer_id()
)
with check (
  public.portal_is_admin()
  or customer_id = public.portal_my_customer_id()
);
