create table if not exists public.portal_consulting_notes (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.portal_customers(id) on delete cascade,
  note_at timestamptz not null default now(),
  note text not null,
  next_action text,
  next_followup_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_at timestamptz not null default now()
);

create index if not exists idx_portal_consulting_notes_customer_time
  on public.portal_consulting_notes (customer_id, note_at desc);

alter table public.portal_consulting_notes enable row level security;

drop policy if exists "portal_consulting_notes_select" on public.portal_consulting_notes;
create policy "portal_consulting_notes_select"
on public.portal_consulting_notes
for select
using (
  public.portal_is_admin()
  or customer_id = public.portal_my_customer_id()
);

drop policy if exists "portal_consulting_notes_write" on public.portal_consulting_notes;
create policy "portal_consulting_notes_write"
on public.portal_consulting_notes
for all
using (
  public.portal_is_admin()
  or customer_id = public.portal_my_customer_id()
)
with check (
  public.portal_is_admin()
  or customer_id = public.portal_my_customer_id()
);
