create extension if not exists pgcrypto;

create table if not exists public.portal_customers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  birth_year integer,
  gender text,
  job text,
  address text,
  email text,
  phone text,
  financial_goal text,
  label text unique,
  first_upload_month text
);

create index if not exists idx_portal_customers_name on public.portal_customers (name);
create index if not exists idx_portal_customers_label on public.portal_customers (label);

create table if not exists public.portal_snapshots (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.portal_customers(id) on delete cascade,
  snapshot_at timestamptz not null default now(),
  snapshot_label text not null default '점검',
  salary_self numeric not null default 0,
  salary_spouse numeric not null default 0,
  other_income numeric not null default 0,
  bonus numeric not null default 0,
  total_monthly_income numeric not null default 0,
  total_expense numeric not null default 0,
  savings_capacity numeric not null default 0,
  savings_ratio numeric not null default 0,
  safe_assets numeric not null default 0,
  investment_assets numeric not null default 0,
  total_financial_assets numeric not null default 0,
  investment_ratio numeric not null default 0,
  real_estate_total numeric not null default 0,
  total_debt numeric not null default 0,
  net_assets numeric not null default 0,
  total_assets numeric not null default 0,
  overall_return_rate numeric not null default 0,
  insurance_premium numeric not null default 0,
  raw_json jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id)
);

create index if not exists idx_portal_snapshots_customer_time on public.portal_snapshots (customer_id, snapshot_at desc);

create table if not exists public.portal_users (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  role text not null check (role in ('admin', 'customer')),
  customer_id bigint references public.portal_customers(id) on delete set null,
  is_active boolean not null default true,
  display_name text
);

create index if not exists idx_portal_users_customer on public.portal_users (customer_id);
create index if not exists idx_portal_users_display_name on public.portal_users (display_name);

create table if not exists public.portal_portfolio_files (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_id bigint not null references public.portal_customers(id) on delete cascade,
  snapshot_id bigint references public.portal_snapshots(id) on delete set null,
  snapshot_label text,
  bucket_name text not null default 'portfolio-files',
  object_path text not null,
  original_name text not null,
  mime_type text,
  file_size bigint not null default 0,
  note text,
  uploaded_by uuid references auth.users(id)
);

create index if not exists idx_portfolio_customer_created on public.portal_portfolio_files (customer_id, created_at desc);

create table if not exists public.portal_execution_tasks (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.portal_customers(id) on delete cascade,
  task_code text not null,
  is_completed boolean not null default false,
  completed_at timestamptz,
  note text,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id),
  unique (customer_id, task_code)
);

create index if not exists idx_execution_tasks_customer on public.portal_execution_tasks (customer_id, updated_at desc);

create table if not exists public.portal_customer_strategy_configs (
  id bigint generated by default as identity primary key,
  customer_id bigint not null unique references public.portal_customers(id) on delete cascade,
  profile_code text not null default 'balanced',
  target_safe_ratio numeric not null default 35,
  target_invest_ratio numeric not null default 45,
  target_real_ratio numeric not null default 20,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create index if not exists idx_strategy_configs_customer on public.portal_customer_strategy_configs (customer_id);

create or replace function public.portal_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.portal_users pu
    where pu.auth_user_id = auth.uid()
      and pu.role = 'admin'
      and pu.is_active = true
  );
$$;

create or replace function public.portal_my_customer_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select pu.customer_id
  from public.portal_users pu
  where pu.auth_user_id = auth.uid()
    and pu.is_active = true
  limit 1;
$$;

create or replace function public.portal_storage_customer_id(object_name text)
returns bigint
language sql
immutable
as $$
  select nullif(substring(object_name from '^customer_([0-9]+)/'), '')::bigint;
$$;

alter table public.portal_customers enable row level security;
alter table public.portal_snapshots enable row level security;
alter table public.portal_users enable row level security;
alter table public.portal_portfolio_files enable row level security;
alter table public.portal_execution_tasks enable row level security;
alter table public.portal_customer_strategy_configs enable row level security;

drop policy if exists "portal_users_self_select" on public.portal_users;
create policy "portal_users_self_select"
on public.portal_users
for select
using (auth_user_id = auth.uid());

drop policy if exists "portal_users_admin_all_select" on public.portal_users;
create policy "portal_users_admin_all_select"
on public.portal_users
for select
using (public.portal_is_admin());

drop policy if exists "portal_users_admin_write" on public.portal_users;
create policy "portal_users_admin_write"
on public.portal_users
for all
using (public.portal_is_admin())
with check (public.portal_is_admin());

drop policy if exists "portal_customers_select" on public.portal_customers;
create policy "portal_customers_select"
on public.portal_customers
for select
using (
  public.portal_is_admin()
  or id = public.portal_my_customer_id()
);

drop policy if exists "portal_customers_admin_write" on public.portal_customers;
create policy "portal_customers_admin_write"
on public.portal_customers
for all
using (public.portal_is_admin())
with check (public.portal_is_admin());

drop policy if exists "portal_snapshots_select" on public.portal_snapshots;
create policy "portal_snapshots_select"
on public.portal_snapshots
for select
using (
  public.portal_is_admin()
  or customer_id = public.portal_my_customer_id()
);

drop policy if exists "portal_snapshots_admin_write" on public.portal_snapshots;
create policy "portal_snapshots_admin_write"
on public.portal_snapshots
for all
using (public.portal_is_admin())
with check (public.portal_is_admin());

drop policy if exists "portal_files_select" on public.portal_portfolio_files;
create policy "portal_files_select"
on public.portal_portfolio_files
for select
using (
  public.portal_is_admin()
  or customer_id = public.portal_my_customer_id()
);

drop policy if exists "portal_files_admin_write" on public.portal_portfolio_files;
create policy "portal_files_admin_write"
on public.portal_portfolio_files
for all
using (public.portal_is_admin())
with check (public.portal_is_admin());

drop policy if exists "portal_execution_tasks_select" on public.portal_execution_tasks;
create policy "portal_execution_tasks_select"
on public.portal_execution_tasks
for select
using (
  public.portal_is_admin()
  or customer_id = public.portal_my_customer_id()
);

drop policy if exists "portal_execution_tasks_write" on public.portal_execution_tasks;
create policy "portal_execution_tasks_write"
on public.portal_execution_tasks
for all
using (
  public.portal_is_admin()
  or customer_id = public.portal_my_customer_id()
)
with check (
  public.portal_is_admin()
  or customer_id = public.portal_my_customer_id()
);

drop policy if exists "portal_strategy_configs_select" on public.portal_customer_strategy_configs;
create policy "portal_strategy_configs_select"
on public.portal_customer_strategy_configs
for select
using (
  public.portal_is_admin()
  or customer_id = public.portal_my_customer_id()
);

drop policy if exists "portal_strategy_configs_write" on public.portal_customer_strategy_configs;
create policy "portal_strategy_configs_write"
on public.portal_customer_strategy_configs
for all
using (
  public.portal_is_admin()
  or customer_id = public.portal_my_customer_id()
)
with check (
  public.portal_is_admin()
  or customer_id = public.portal_my_customer_id()
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'portfolio-files',
  'portfolio-files',
  false,
  26214400,
  array['application/pdf', 'image/png', 'image/jpeg', 'image/webp', 'image/gif']
)
on conflict (id) do nothing;

drop policy if exists "portfolio_objects_select" on storage.objects;
create policy "portfolio_objects_select"
on storage.objects
for select
using (
  bucket_id = 'portfolio-files'
  and (
    public.portal_is_admin()
    or public.portal_storage_customer_id(name) = public.portal_my_customer_id()
  )
);

drop policy if exists "portfolio_objects_admin_insert" on storage.objects;
create policy "portfolio_objects_admin_insert"
on storage.objects
for insert
with check (
  bucket_id = 'portfolio-files'
  and public.portal_is_admin()
);

drop policy if exists "portfolio_objects_admin_update" on storage.objects;
create policy "portfolio_objects_admin_update"
on storage.objects
for update
using (
  bucket_id = 'portfolio-files'
  and public.portal_is_admin()
)
with check (
  bucket_id = 'portfolio-files'
  and public.portal_is_admin()
);

drop policy if exists "portfolio_objects_admin_delete" on storage.objects;
create policy "portfolio_objects_admin_delete"
on storage.objects
for delete
using (
  bucket_id = 'portfolio-files'
  and public.portal_is_admin()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.portal_users (auth_user_id, role, is_active, display_name)
  values (
    new.id,
    'customer',
    false,
    nullif(
      btrim(coalesce(
        new.raw_user_meta_data ->> 'full_name',
        new.raw_user_meta_data ->> 'display_name',
        new.raw_user_meta_data ->> 'name'
      )),
      ''
    )
  )
  on conflict (auth_user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
