create table if not exists public.portal_customer_strategy_configs (
  id bigint generated by default as identity primary key,
  customer_id bigint not null unique references public.portal_customers(id) on delete cascade,
  profile_code text not null default 'balanced',
  target_safe_ratio numeric not null default 35,
  target_invest_ratio numeric not null default 45,
  target_real_ratio numeric not null default 20,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create index if not exists idx_strategy_configs_customer
  on public.portal_customer_strategy_configs (customer_id);

alter table public.portal_customer_strategy_configs enable row level security;

drop policy if exists "portal_strategy_configs_select" on public.portal_customer_strategy_configs;
create policy "portal_strategy_configs_select"
on public.portal_customer_strategy_configs
for select
using (
  public.portal_is_admin()
  or customer_id = public.portal_my_customer_id()
);

drop policy if exists "portal_strategy_configs_write" on public.portal_customer_strategy_configs;
create policy "portal_strategy_configs_write"
on public.portal_customer_strategy_configs
for all
using (
  public.portal_is_admin()
  or customer_id = public.portal_my_customer_id()
)
with check (
  public.portal_is_admin()
  or customer_id = public.portal_my_customer_id()
);
